<?php $url_header=substr($_SERVER["REQUEST_URI"], strpos($_SERVER["REQUEST_URI"], '/')+1);
?><?php if (strpos($url_header, "servicos/") !==false) {
    ?><header id="header"><div class="top"><div class="grid_3" style="float: right; "><a href="mailto:contato@endall.com.br" style="color:white;" target="_blank" rel="noopener" rel="noreferrer"><img src="../images/icon-mail-br.svg" alt="Email da Endall Inspeções">contato@endall.com.br</a></div><div class="grid_2" style="float: right; "></div><div class="grid_2 nophone" style="float: right; "><a href="tel:1931320658" style="color:white;" target="_blank" rel="noopener" rel="noreferrer"><img class="lozad" src="../images/icon-phone-br.svg" alt="Telefone da Endall Inspeções" data-loaded="true">(19) 3132-0658</a></div></div><div class="inner"><a class="logo" href="../index.php"><img src="../images/logo.png" alt="Logo Endall Inspeções e Serviços" width="200" height="66"></a><nav id="nav"><ul><li><a href="../index.php">Home</a></li><li><a href="../endall-inspecoes-servicos.php">Sobre Nós</a></li><li><a href="../servicos-endall-inspecoes.php">Serviços</a><ul><a href="endoscopia-industrial.php">Endoscopia/Videoscopia Industrial</a></li><li><a href="video-inspecao-rede-efluentes.php">Video Inspeção em Rede de Efluentes </a></li><li><a href="boroscopia-turbinas.php">Boroscopia em Turbinas</a></li><li><a href="boroscopia-redutores.php">Boroscopia em Redutores</a></li><li><a href="endoscopia-tubulacoes-sanitarias.php">Endoscopia de Tubulações Sanitárias</a></li><li><a href="ensaio-liquido-penetrante.php">Ensaio por Líquido Penetrante</a></li><li><a href="ensaio-particulas-magneticas.php">Ensaio por Partículas Magnéticas</a></li><li><a href="ensaio-ultrassom.php">Ensaio por Ultrassom</a></li><li><a href="inspecao-fiscalizacao-fabricacao.php">Inspeção / Fiscalização de Fabricação </a></li><li><a href="nr-13.php">NR-13</a></li><li><a href="documentacao-em-soldagem.php">Documentação em Soldagem</a></li></ul></li><li><a href="../locacao-equipamentos-boroscopia-endoscopia.php">Equipamentos</a><ul><a href="../locacao-equipamentos-boroscopia-endoscopia.php">Locação</a></li></ul></li><li><a href="../catalogo/index.php">Yateks Brasil</a></li><li><a href="../contato-endall-inspecoes.php" class="btn-orcamento">Solicite um orçamento</a></li></ul></nav></div></header><?php
}

else if (strpos($url_header, "equipamentos/") !==false) {
    ?><header id="header"><div class="top"><div class="grid_3" style="float: right; "><a href="mailto:contato@endall.com.br" style="color:white;"><img src="../images/icon-mail-br.svg" alt="Email da Endall Inspeções">contato@endall.com.br</a></div><div class="grid_2" style="float: right; "></div><div class="grid_2 nophone" style="float: right; "><a href="tel:1931320658" style="color:white;" target="_blank" rel="noopener" rel="noreferrer"><img class="lozad" src="../images/icon-phone-br.svg" alt="Telefone da Endall Inspeções" data-loaded="true">(19) 3132-0658</a></div></div><div class="inner"><a class="logo" href="../index.php"><img src="../images/logo.png" alt="Logo Endall Inspeções e Serviços" width="200" height="66"></a><nav id="nav"><ul><li><a href="../index.php">Home</a></li><li><a href="../endall-inspecoes-servicos.php">Sobre Nós</a></li><li><a href="../servicos-endall-inspecoes.php">Serviços</a><ul><a href="../servicos/endoscopia-industrial.php">Endoscopia/Videoscopia Industrial</a></li><li><a href="../servicos/video-inspecao-rede-efluentes.php">Video Inspeção em Rede de Efluentes </a></li><li><a href="../servicos/boroscopia-turbinas.php">Boroscopia em Turbinas</a></li><li><a href="../servicos/boroscopia-redutores.php">Boroscopia em Redutores</a></li><li><a href="../servicos/endoscopia-tubulacoes-sanitarias.php">Endoscopia de Tubulações Sanitárias</a></li><li><a href="../servicos/ensaio-liquido-penetrante.php">Ensaio por Líquido Penetrante</a></li><li><a href="../servicos/ensaio-particulas-magneticas.php">Ensaio por Partículas Magnéticas</a></li><li><a href="../servicos/ensaio-ultrassom.php">Ensaio por Ultrassom</a></li><li><a href="../servicos/inspecao-fiscalizacao-fabricacao.php">Inspeção / Fiscalização de Fabricação </a></li><li><a href="../servicos/nr-13.php">NR-13</a></li><li><a href="../servicos/documentacao-em-soldagem.php">Documentação em Soldagem</a></li></ul></li><li><a href="../locacao-equipamentos-boroscopia-endoscopia.php">Equipamentos</a><ul><a href="../locacao-equipamentos-boroscopia-endoscopia.php">Locação</a></li></ul></li><li><a href="../catalogo/index.php">Yateks Brasil</a></li><li><a href="../contato-endall-inspecoes.php" class="btn-orcamento">Solicite um orçamento</a></li></ul></nav></div></header><?php
}

else {
    ?><header id="header"><div class="top"><div class="grid_3" style="float: right; "><a href="mailto:contato@endall.com.br" style="color:white;"><img src="images/icon-mail-br.svg" alt="Email da Endall Inspeções">contato@endall.com.br</a></div><div class="grid_2" style="float: right; "></div><div class="grid_2 nophone" style="float: right; "><a href="tel:1931320658" style="color:white;" target="_blank" rel="noopener" rel="noreferrer"><img class="lozad" src="images/icon-phone-br.svg" alt="Telefone da Endall Inspeções" data-loaded="true">(19) 3132-0658</a></div></div><div class="inner"><a class="logo" href="index.php"><img src="images/logo.png" alt="Logo Endall Inspeções e Serviços" width="200" height="66"></a><nav id="nav"><ul><li><a href="index.php">Home</a></li><li><a href="endall-inspecoes-servicos.php">Sobre Nós</a></li><li><a href="servicos-endall-inspecoes.php">Serviços</a><ul><li><a href="servicos/endoscopia-industrial.php">Endoscopia/Videoscopia Industrial</a></li><li><a href="servicos/video-inspecao-rede-efluentes.php">Video Inspeção em Rede de Efluentes </a></li><li><a href="servicos/boroscopia-turbinas.php">Boroscopia em Turbinas</a></li><li><a href="servicos/boroscopia-redutores.php">Boroscopia em Redutores</a></li><li><a href="servicos/endoscopia-tubulacoes-sanitarias.php">Endoscopia de Tubulações Sanitárias</a></li><li><a href="servicos/ensaio-liquido-penetrante.php">Ensaio por Líquido Penetrante</a></li><li><a href="servicos/ensaio-particulas-magneticas.php">Ensaio por Partículas Magnéticas</a></li><li><a href="servicos/ensaio-ultrassom.php">Ensaio por Ultrassom</a></li><li><a href="servicos/inspecao-fiscalizacao-fabricacao.php">Inspeção / Fiscalização de Fabricação </a></li><li><a href="servicos/nr-13.php">NR-13</a></li><li><a href="servicos/documentacao-em-soldagem.php">Documentação em Soldagem</a></li></ul><li><a href="locacao-equipamentos-boroscopia-endoscopia.php">Equipamentos</a><ul><a href="locacao-equipamentos-boroscopia-endoscopia.php">Locação</a></li></ul></li><li><a href="catalogo/index.php">Yateks Brasil</a></li><li><a href="contato-endall-inspecoes.php" class="btn-orcamento">Solicite um orçamento</a></li></ul></nav></div></header><?php
}

?>